import type { TransitionPhase } from '@/types/database';

export interface DefaultTask {
  id: string;
  title: string;
  description: string;
  phase: TransitionPhase;
  category: 'admin' | 'career' | 'benefits' | 'network' | 'skills' | 'personal';
  dueOffsetDays: number; // Days before ETS this should be done
  whyItMatters: string;
  resources?: { label: string; url: string }[];
}

// Category icons mapping
export const CATEGORY_INFO: Record<DefaultTask['category'], { label: string; color: string }> = {
  admin: { label: 'Administrative', color: 'bg-blue-500' },
  career: { label: 'Career Planning', color: 'bg-green-500' },
  benefits: { label: 'Benefits', color: 'bg-purple-500' },
  network: { label: 'Networking', color: 'bg-orange-500' },
  skills: { label: 'Skills & Training', color: 'bg-cyan-500' },
  personal: { label: 'Personal', color: 'bg-pink-500' },
};

// Default tasks aligned with 24-month timeline from uploaded resources
export const DEFAULT_TASKS: DefaultTask[] = [
  // 12-9 MONTHS OUT (Early Planning Phase)
  {
    id: '12-9-1',
    title: 'Register with eBenefits',
    description: 'Create your eBenefits account to access VA services and benefits information.',
    phase: '12_to_9_months',
    category: 'benefits',
    dueOffsetDays: 365,
    whyItMatters: 'eBenefits is your gateway to understanding and claiming all the benefits you\'ve earned. Starting early gives you time to navigate the system.',
    resources: [{ label: 'eBenefits Portal', url: 'https://www.ebenefits.va.gov' }],
  },
  {
    id: '12-9-2',
    title: 'Complete Pre-Separation Counseling',
    description: 'Schedule and complete your mandatory pre-separation counseling to begin the formal transition process.',
    phase: '12_to_9_months',
    category: 'admin',
    dueOffsetDays: 365,
    whyItMatters: 'This mandatory step starts your official transition timeline and ensures you understand all required steps.',
  },
  {
    id: '12-9-3',
    title: 'Begin Individual Transition Plan (ITP)',
    description: 'Start developing your written transition plan with goals, timelines, and action items.',
    phase: '12_to_9_months',
    category: 'career',
    dueOffsetDays: 350,
    whyItMatters: 'A written plan with goals and timelines is one of the 5 most important elements of a successful transition.',
  },
  {
    id: '12-9-4',
    title: 'Get LinkedIn Premium (Free for Military)',
    description: 'Activate your free 1-year LinkedIn Premium account using your military email.',
    phase: '12_to_9_months',
    category: 'network',
    dueOffsetDays: 365,
    whyItMatters: 'LinkedIn is essential for civilian job searching. Premium features help you connect with recruiters and see who\'s viewing your profile.',
    resources: [{ label: 'LinkedIn for Veterans', url: 'https://linkedin.com/veterans' }],
  },
  {
    id: '12-9-5',
    title: 'Start Daily Journal for Self-Assessment',
    description: 'Begin journaling to identify what makes you feel valued and significant. This helps clarify career direction.',
    phase: '12_to_9_months',
    category: 'personal',
    dueOffsetDays: 365,
    whyItMatters: 'Journaling helps you gain clarity on issues, discover patterns, and explore solutions for your future career.',
  },
  {
    id: '12-9-6',
    title: 'Research Career Paths & Complete Career Taste Test',
    description: 'Explore different career fields by speaking with mentors in areas of interest. Sample careers like a buffet.',
    phase: '12_to_9_months',
    category: 'career',
    dueOffsetDays: 340,
    whyItMatters: 'One of the best ways to discover careers is to talk to people doing those jobs. The cost is low and rewards are unlimited.',
    resources: [{ label: 'My Next Move', url: 'https://mynextmove.org' }],
  },
  {
    id: '12-9-7',
    title: 'Schedule Meeting with PCM',
    description: 'Meet with your Primary Care Manager to review medical history and get recommendations for treatment/documentation.',
    phase: '12_to_9_months',
    category: 'benefits',
    dueOffsetDays: 335,
    whyItMatters: 'Documenting any service-connected conditions early is crucial for VA disability claims.',
  },
  {
    id: '12-9-8',
    title: 'Begin Deliberate Networking',
    description: 'Start building your professional network. Connect with veterans who have transitioned, industry professionals, and mentors.',
    phase: '12_to_9_months',
    category: 'network',
    dueOffsetDays: 365,
    whyItMatters: 'Networking is the #1 recommended element of a successful transition. Who you know matters.',
    resources: [
      { label: 'ACP (American Corporate Partners)', url: 'https://acp-usa.org' },
      { label: 'Veterati', url: 'https://veterati.com' },
    ],
  },
  
  // 9-6 MONTHS OUT
  {
    id: '9-6-1',
    title: 'Complete TAP/TAPS Workshop',
    description: 'Attend the full Transition Assistance Program workshop series.',
    phase: '9_to_6_months',
    category: 'admin',
    dueOffsetDays: 270,
    whyItMatters: 'TAP provides essential resources and mandatory training for your transition. Many services won\'t be available until completed.',
  },
  {
    id: '9-6-2',
    title: 'Narrow Career Field and Target Location',
    description: 'Based on your research, narrow down to 1-2 career paths and determine your target location.',
    phase: '9_to_6_months',
    category: 'career',
    dueOffsetDays: 260,
    whyItMatters: 'Focusing your efforts allows you to become an expert in your target field rather than spreading yourself thin.',
  },
  {
    id: '9-6-3',
    title: 'Build Your Resume (First Draft)',
    description: 'Create your first resume draft translating military experience to civilian language.',
    phase: '9_to_6_months',
    category: 'career',
    dueOffsetDays: 250,
    whyItMatters: 'Translating your skills is the hardest part of a successful transition. Start early to practice and refine.',
  },
  {
    id: '9-6-4',
    title: 'Research SkillBridge/CSP Opportunities',
    description: 'Identify SkillBridge programs aligned with your career goals and understand eligibility requirements.',
    phase: '9_to_6_months',
    category: 'skills',
    dueOffsetDays: 240,
    whyItMatters: 'SkillBridge provides hands-on training with civilian employers while still receiving military pay and benefits.',
    resources: [{ label: 'DoD SkillBridge', url: 'https://dodskillbridge.com' }],
  },
  {
    id: '9-6-5',
    title: 'Schedule Legal Appointment',
    description: 'Schedule with JAG for end-of-life planning, living will, will, and powers of attorney.',
    phase: '9_to_6_months',
    category: 'personal',
    dueOffsetDays: 230,
    whyItMatters: 'Legal documents done through JAG are free. After separation, these services can cost hundreds of dollars.',
  },
  {
    id: '9-6-6',
    title: 'Complete Eye Exam & Get Glasses',
    description: 'Get your final eye exam and order your last pair of military-covered glasses.',
    phase: '9_to_6_months',
    category: 'benefits',
    dueOffsetDays: 220,
    whyItMatters: 'Free benefit while in service. Vision care post-military can be expensive out of pocket.',
  },
  {
    id: '9-6-7',
    title: 'Complete Final Dental Work',
    description: 'Schedule and complete any needed dental work before separation.',
    phase: '9_to_6_months',
    category: 'benefits',
    dueOffsetDays: 220,
    whyItMatters: 'Dental work is fully covered while in service. TRICARE Dental after separation has limitations and costs.',
  },
  {
    id: '9-6-8',
    title: 'Start Job Shadow/Mentorship Program',
    description: 'Through your network, arrange job shadows or informational interviews in your target field.',
    phase: '9_to_6_months',
    category: 'network',
    dueOffsetDays: 210,
    whyItMatters: 'Seeing the day-to-day reality of a job helps confirm your career choice and builds valuable connections.',
  },

  // 6-3 MONTHS OUT
  {
    id: '6-3-1',
    title: 'Apply to SkillBridge/CSP Programs',
    description: 'Submit applications for your selected SkillBridge programs with commander approval.',
    phase: '6_to_3_months',
    category: 'skills',
    dueOffsetDays: 180,
    whyItMatters: 'Programs fill up quickly. Early application increases your chances of getting your preferred opportunity.',
  },
  {
    id: '6-3-2',
    title: 'Finalize Resume and LinkedIn',
    description: 'Polish your resume and LinkedIn profile. Get feedback from mentors and your network.',
    phase: '6_to_3_months',
    category: 'career',
    dueOffsetDays: 170,
    whyItMatters: 'A polished resume and LinkedIn profile are your first impression to potential employers.',
  },
  {
    id: '6-3-3',
    title: 'Begin Applying to Jobs',
    description: 'Start submitting applications to positions aligned with your target career.',
    phase: '6_to_3_months',
    category: 'career',
    dueOffsetDays: 160,
    whyItMatters: 'The job search takes time. Starting early gives you more opportunities and reduces stress.',
  },
  {
    id: '6-3-4',
    title: 'Practice Interviewing Weekly',
    description: 'Conduct mock interviews with mentors, use AI tools, and practice your STAR stories.',
    phase: '6_to_3_months',
    category: 'skills',
    dueOffsetDays: 150,
    whyItMatters: 'Practice is essential. The more you interview, the more comfortable and confident you\'ll become.',
  },
  {
    id: '6-3-5',
    title: 'Determine Insurance Requirements',
    description: 'Research TRICARE options (Prime vs Select), life insurance (VGLI), dental (DELTA), and supplemental coverage.',
    phase: '6_to_3_months',
    category: 'benefits',
    dueOffsetDays: 140,
    whyItMatters: 'Understanding your options prevents gaps in coverage and unexpected costs after separation.',
    resources: [{ label: 'TRICARE', url: 'https://www.tricare.mil/mybenefit' }],
  },
  {
    id: '6-3-6',
    title: 'Open My Social Security Account',
    description: 'Create your Social Security account to verify earnings record and understand future benefits.',
    phase: '6_to_3_months',
    category: 'benefits',
    dueOffsetDays: 130,
    whyItMatters: 'Verify your military earnings are correctly recorded. Errors can affect future Social Security benefits.',
    resources: [{ label: 'My Social Security', url: 'https://www.ssa.gov/myaccount' }],
  },
  {
    id: '6-3-7',
    title: 'Attend Virtual and In-Person Job Fairs',
    description: 'Participate in veteran-focused career fairs and networking events.',
    phase: '6_to_3_months',
    category: 'network',
    dueOffsetDays: 120,
    whyItMatters: 'Job fairs provide direct access to veteran-friendly employers actively looking to hire.',
    resources: [{ label: 'Hiring Our Heroes', url: 'https://hiringourheroes.org' }],
  },
  {
    id: '6-3-8',
    title: 'Develop Duties Off-Ramp Plan',
    description: 'Work with your supervisor to develop a plan for transitioning your duties and responsibilities.',
    phase: '6_to_3_months',
    category: 'admin',
    dueOffsetDays: 110,
    whyItMatters: 'A smooth handover protects your reputation and relationship with your command.',
  },

  // 90-30 DAYS
  {
    id: '90-30-1',
    title: 'Schedule VA BDD Claim',
    description: 'Schedule Benefits Delivery at Discharge (BDD) exam to file disability claims before separation.',
    phase: '90_to_30_days',
    category: 'benefits',
    dueOffsetDays: 90,
    whyItMatters: 'BDD allows faster processing of disability claims, with decisions potentially ready by ETS.',
  },
  {
    id: '90-30-2',
    title: 'Send 5+ Applications Per Week',
    description: 'Increase job application volume. Follow up on pending applications.',
    phase: '90_to_30_days',
    category: 'career',
    dueOffsetDays: 85,
    whyItMatters: 'Job searching is a numbers game. More applications increase your chances of landing interviews.',
  },
  {
    id: '90-30-3',
    title: 'Conduct Capstone Appointment',
    description: 'Complete your Capstone review to verify all transition requirements are met.',
    phase: '90_to_30_days',
    category: 'admin',
    dueOffsetDays: 75,
    whyItMatters: 'Capstone verifies you\'ve met Career Readiness Standards and are prepared for transition.',
  },
  {
    id: '90-30-4',
    title: 'Schedule ID Card Appointments',
    description: 'Schedule appointments for new ID cards (retiree/veteran) for you and dependents.',
    phase: '90_to_30_days',
    category: 'admin',
    dueOffsetDays: 60,
    whyItMatters: 'ID cards are needed for continued access to benefits and installations.',
  },
  {
    id: '90-30-5',
    title: 'Begin Final Out-Processing',
    description: 'Start clearing post/base. Gather all required documents for final out.',
    phase: '90_to_30_days',
    category: 'admin',
    dueOffsetDays: 50,
    whyItMatters: 'Final out-processing takes time. Starting early prevents last-minute stress.',
  },
  {
    id: '90-30-6',
    title: 'Negotiate Job Offers',
    description: 'For any offers received, negotiate salary, benefits, start date, and other terms.',
    phase: '90_to_30_days',
    category: 'career',
    dueOffsetDays: 45,
    whyItMatters: 'Veterans often undervalue themselves. Negotiation can significantly impact your starting compensation.',
  },
  {
    id: '90-30-7',
    title: 'Apply for SGLI to VGLI Conversion',
    description: 'If desired, submit application to convert SGLI to VGLI life insurance.',
    phase: '90_to_30_days',
    category: 'benefits',
    dueOffsetDays: 40,
    whyItMatters: 'You have 120 days post-separation to convert without medical exam. After that, it may be denied.',
  },

  // TERMINAL/PTDY PHASE
  {
    id: 'term-1',
    title: 'Complete Final Out-Processing',
    description: 'Finish all out-processing requirements. Verify DD214 accuracy before signing.',
    phase: 'terminal_ptdy',
    category: 'admin',
    dueOffsetDays: 30,
    whyItMatters: 'Your DD214 is one of the most important documents you\'ll ever have. Errors are difficult to correct later.',
  },
  {
    id: 'term-2',
    title: 'Finalize Job Offers',
    description: 'Accept your preferred offer. Confirm start date and complete any pre-employment requirements.',
    phase: 'terminal_ptdy',
    category: 'career',
    dueOffsetDays: 25,
    whyItMatters: 'Having a job secured before terminal leave reduces financial stress and allows you to focus on moving.',
  },
  {
    id: 'term-3',
    title: 'Enroll in TRICARE',
    description: 'Enroll in TRICARE Retired/Reserve Select once DEERS reflects your status.',
    phase: 'terminal_ptdy',
    category: 'benefits',
    dueOffsetDays: 20,
    whyItMatters: 'Timely enrollment prevents gaps in healthcare coverage for you and your family.',
  },
  {
    id: 'term-4',
    title: 'Schedule Transportation/Move',
    description: 'Finalize moving arrangements. You have up to 1 year after retirement with possible extensions.',
    phase: 'terminal_ptdy',
    category: 'personal',
    dueOffsetDays: 15,
    whyItMatters: 'Military moves are a valuable benefit. Plan carefully to maximize your entitlements.',
    resources: [{ label: 'Move.mil', url: 'https://www.move.mil' }],
  },
  {
    id: 'term-5',
    title: 'Prepare for Day 1 at New Job',
    description: 'Research your new company, understand the culture, prepare your work wardrobe.',
    phase: 'terminal_ptdy',
    category: 'career',
    dueOffsetDays: 10,
    whyItMatters: 'First impressions matter. Being prepared shows professionalism and commitment.',
  },

  // POST-ETS PHASE
  {
    id: 'post-1',
    title: 'Continue Networking',
    description: 'Stay connected with your network. You never know when opportunities will arise.',
    phase: 'post_ets',
    category: 'network',
    dueOffsetDays: -7,
    whyItMatters: 'Your network doesn\'t stop being valuable after ETS. Continue building relationships.',
  },
  {
    id: 'post-2',
    title: 'Follow Up on VA Claims',
    description: 'Check status of any pending VA claims and provide additional documentation if requested.',
    phase: 'post_ets',
    category: 'benefits',
    dueOffsetDays: -14,
    whyItMatters: 'Staying proactive with claims can speed up the process and ensure you receive entitled benefits.',
  },
  {
    id: 'post-3',
    title: 'Update Resume with Civilian Experience',
    description: 'Once you start your new role, update your resume with civilian accomplishments.',
    phase: 'post_ets',
    category: 'career',
    dueOffsetDays: -30,
    whyItMatters: 'Keep your resume current. You never know when the next opportunity will present itself.',
  },
];

export function getTasksByPhase(phase: TransitionPhase): DefaultTask[] {
  return DEFAULT_TASKS.filter(task => task.phase === phase);
}

export function getAllCategories(): DefaultTask['category'][] {
  return ['admin', 'career', 'benefits', 'network', 'skills', 'personal'];
}
